POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "customerDocument": "CC-1234567890",
  "productId": "0ec1dbfb-e180-471a-88af-d277c8af150d",
  "quantity": 4,
  "additionalInfo": ""
}

###

PATCH http://localhost:8080/api/v1/orders/0bcadcf5-6f2a-45c6-9bb7-110a180fea1b/delivered/2012-02-12T19:15:00
###